name: root
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  '_nb_ext_conf=0.3.0=py27_0'
- !!python/unicode
  'alabaster=0.7.9=py27_0'
- !!python/unicode
  'anaconda-client=1.6.0=py27_0'
- !!python/unicode
  'apptools=4.4.0=py27_0'
- !!python/unicode
  'astroid=1.4.9=py27_0'
- !!python/unicode
  'babel=2.3.4=py27_0'
- !!python/unicode
  'backports=1.0=py27_0'
- !!python/unicode
  'backports_abc=0.5=py27_0'
- !!python/unicode
  'beautifulsoup4=4.5.3=py27_0'
- !!python/unicode
  'cffi=1.9.1=py27_0'
- !!python/unicode
  'clyent=1.2.2=py27_0'
- !!python/unicode
  'colorama=0.3.7=py27_0'
- !!python/unicode
  'conda=4.3.8=py27_0'
- !!python/unicode
  'conda-env=2.6.0=0'
- !!python/unicode
  'configobj=5.0.6=py27_0'
- !!python/unicode
  'configparser=3.5.0=py27_0'
- !!python/unicode
  'console_shortcut=0.1.1=py27_1'
- !!python/unicode
  'cryptography=1.7.1=py27_0'
- !!python/unicode
  'cycler=0.10.0=py27_0'
- !!python/unicode
  'decorator=4.0.10=py27_1'
- !!python/unicode
  'docutils=0.12=py27_2'
- !!python/unicode
  'entrypoints=0.2.2=py27_0'
- !!python/unicode
  'enum34=1.1.6=py27_0'
- !!python/unicode
  'envisage=4.5.1=py27_0'
- !!python/unicode
  'functools32=3.2.3.2=py27_0'
- !!python/unicode
  'get_terminal_size=1.0.0=py27_0'
- !!python/unicode
  'graphviz=2.38.0=4'
- !!python/unicode
  'icu=57.1=vc9_0'
- !!python/unicode
  'idna=2.2=py27_0'
- !!python/unicode
  'imagesize=0.7.1=py27_0'
- !!python/unicode
  'ipaddress=1.0.18=py27_0'
- !!python/unicode
  'ipykernel=4.5.2=py27_0'
- !!python/unicode
  'ipython=5.1.0=py27_0'
- !!python/unicode
  'ipython_genutils=0.1.0=py27_0'
- !!python/unicode
  'ipywidgets=5.2.2=py27_0'
- !!python/unicode
  'isort=4.2.5=py27_0'
- !!python/unicode
  'jedi=0.9.0=py27_1'
- !!python/unicode
  'jinja2=2.8.1=py27_0'
- !!python/unicode
  'jpeg=8d=vc9_2'
- !!python/unicode
  'jsonschema=2.5.1=py27_0'
- !!python/unicode
  'jupyter=1.0.0=py27_3'
- !!python/unicode
  'jupyter_client=4.4.0=py27_0'
- !!python/unicode
  'jupyter_console=5.0.0=py27_0'
- !!python/unicode
  'jupyter_core=4.2.1=py27_0'
- !!python/unicode
  'lazy-object-proxy=1.2.2=py27_0'
- !!python/unicode
  'libpng=1.6.27=vc9_0'
- !!python/unicode
  'markupsafe=0.23=py27_2'
- !!python/unicode
  'matplotlib=1.5.1=np111py27_0'
- !!python/unicode
  'mayavi=4.5.0=py27_0'
- !!python/unicode
  'menuinst=1.4.2=py27_1'
- !!python/unicode
  'mistune=0.7.3=py27_0'
- !!python/unicode
  'mkl=11.3.3=1'
- !!python/unicode
  'nb_anacondacloud=1.2.0=py27_0'
- !!python/unicode
  'nb_conda=2.0.0=py27_0'
- !!python/unicode
  'nb_conda_kernels=2.0.0=py27_0'
- !!python/unicode
  'nbconvert=4.2.0=py27_0'
- !!python/unicode
  'nbformat=4.2.0=py27_0'
- !!python/unicode
  'nbpresent=3.0.2=py27_0'
- !!python/unicode
  'networkx=1.10=py27_0'
- !!python/unicode
  'nose=1.3.7=py27_1'
- !!python/unicode
  'notebook=4.3.0=py27_0'
- !!python/unicode
  'numexpr=2.6.1=np111py27_1'
- !!python/unicode
  'numpy=1.11.2=py27_0'
- !!python/unicode
  'openssl=1.0.2j=vc9_0'
- !!python/unicode
  'pandas=0.19.2=np111py27_1'
- !!python/unicode
  'path.py=9.0.1=py27_0'
- !!python/unicode
  'pathlib2=2.1.0=py27_0'
- !!python/unicode
  'patsy=0.4.1=py27_0'
- !!python/unicode
  'pep8=1.7.0=py27_0'
- !!python/unicode
  'pickleshare=0.7.4=py27_0'
- !!python/unicode
  'pip=8.1.2=py27_0'
- !!python/unicode
  'prompt_toolkit=1.0.9=py27_0'
- !!python/unicode
  'psutil=5.0.1=py27_0'
- !!python/unicode
  'pyasn1=0.1.9=py27_0'
- !!python/unicode
  'pycosat=0.6.1=py27_1'
- !!python/unicode
  'pycparser=2.17=py27_0'
- !!python/unicode
  'pycrypto=2.6.1=py27_4'
- !!python/unicode
  'pyface=5.1.0=py27_0'
- !!python/unicode
  'pyflakes=1.4.0=py27_0'
- !!python/unicode
  'pygments=2.1.3=py27_0'
- !!python/unicode
  'pylint=1.6.4=py27_1'
- !!python/unicode
  'pyopenssl=16.2.0=py27_0'
- !!python/unicode
  'pyparsing=2.1.4=py27_0'
- !!python/unicode
  'pyqt=4.10.4=py27_1'
- !!python/unicode
  'python=2.7.12=0'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'pytz=2016.10=py27_0'
- !!python/unicode
  'pywin32=220=py27_1'
- !!python/unicode
  'pyyaml=3.12=py27_0'
- !!python/unicode
  'pyzmq=16.0.2=py27_0'
- !!python/unicode
  'qt=5.6.2=vc9_0'
- !!python/unicode
  'qtconsole=4.2.1=py27_0'
- !!python/unicode
  'requests=2.12.4=py27_0'
- !!python/unicode
  'rope=0.9.4=py27_1'
- !!python/unicode
  'ruamel_yaml=0.11.14=py27_0'
- !!python/unicode
  'scipy=0.18.1=np111py27_0'
- !!python/unicode
  'seaborn=0.7.1=py27_0'
- !!python/unicode
  'setuptools=27.2.0=py27_1'
- !!python/unicode
  'simplegeneric=0.8.1=py27_1'
- !!python/unicode
  'singledispatch=3.4.0.3=py27_0'
- !!python/unicode
  'sip=4.18=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'snowballstemmer=1.2.1=py27_0'
- !!python/unicode
  'sphinx=1.5.1=py27_0'
- !!python/unicode
  'spyder=2.3.9=py27_1'
- !!python/unicode
  'ssl_match_hostname=3.4.0.2=py27_1'
- !!python/unicode
  'statsmodels=0.6.1=np111py27_1'
- !!python/unicode
  'tk=8.5.18=vc9_0'
- !!python/unicode
  'tornado=4.4.2=py27_0'
- !!python/unicode
  'traitlets=4.3.1=py27_0'
- !!python/unicode
  'traits=4.6.0=py27_0'
- !!python/unicode
  'traitsui=5.1.0=py27_0'
- !!python/unicode
  'vs2008_runtime=9.00.30729.1=2'
- !!python/unicode
  'vtk=6.3.0=py27_1'
- !!python/unicode
  'wcwidth=0.1.7=py27_0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'widgetsnbextension=1.2.6=py27_0'
- !!python/unicode
  'win_unicode_console=0.5=py27_0'
- !!python/unicode
  'wrapt=1.10.8=py27_0'
- !!python/unicode
  'zlib=1.2.8=vc9_3'
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - dropbox==6.9.0
  - future==0.16.0
  - git-remote-dropbox==0.2.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.9
  - pydotplus==2.0.2
  - pyinstaller==3.2.1
  - typing==3.5.3.0
  - urllib3==1.19.1
  - win-unicode-console==0.5
